# Part of MHC. See LICENSE file for full copyright and licensing details.

from . import models
from . import wizard
from ._account_setup import (
    PAYROLL_ACCOUNTS,
    SAL_JOURNAL,
    ensure_payroll_accounts,
    ensure_sal_journal,
    assign_journal_to_structures,
)


def _post_init_hook(env):
    """Post-installation setup for l10n_ca_hr_payroll_except_QC.

    Responsibilities
    ----------------
    1. Archive default salary rules auto-generated by hr_payroll that
       conflict with our custom BASIC / GROSS / NET rules.
    2. For every Canadian company (country_id.code == 'CA'):
       a. Create the 17 payroll GL accounts (idempotent by ``code``).
       b. Create the SAL Salary Journal if absent.
       c. Assign the SAL journal to the Canadian payroll structures when
          the ``hr_payroll_account`` bridge is installed.
    """
    # ------------------------------------------------------------------
    # 1. Archive conflicting default salary rules (original logic)
    # ------------------------------------------------------------------
    ca_structure = env.ref(
        'l10n_ca_hr_payroll.hr_payroll_structure_ca_employee_salary',
        raise_if_not_found=False,
    )
    own_hourly = env.ref(
        'l10n_ca_hr_payroll_except_QC.hr_payroll_structure_ca_employee_salary',
        raise_if_not_found=False,
    )
    own_salaried = env.ref(
        'l10n_ca_hr_payroll_except_QC.hr_payroll_structure_ca_employee_salary_salaried',
        raise_if_not_found=False,
    )

    structure_ids = []
    if ca_structure:
        structure_ids.append(ca_structure.id)
    if own_hourly:
        structure_ids.append(own_hourly.id)
    if own_salaried:
        structure_ids.append(own_salaried.id)

    if structure_ids:
        default_codes = [
            'BASIC', 'GROSS', 'NET',
            'ATTACH_SALARY', 'ASSIG_SALARY',
            'CHILD_SUPPORT', 'DEDUCTION', 'REIMBURSEMENT',
        ]
        own_rule_xmlids = [
            'l10n_ca_hr_payroll_except_QC.salary_rule_ca_basic',
            'l10n_ca_hr_payroll_except_QC.salary_rule_ca_gross',
            'l10n_ca_hr_payroll_except_QC.salary_rule_ca_net',
        ]
        own_rule_ids = set()
        for xmlid in own_rule_xmlids:
            rule = env.ref(xmlid, raise_if_not_found=False)
            if rule:
                own_rule_ids.add(rule.id)

        default_rules = env['hr.salary.rule'].search([
            ('struct_id', 'in', structure_ids),
            ('code', 'in', default_codes),
        ])
        rules_to_archive = default_rules.filtered(lambda r: r.id not in own_rule_ids)
        if rules_to_archive:
            rules_to_archive.active = False

    # ------------------------------------------------------------------
    # 2. Accounting setup — accounts, journal, structure assignment
    # ------------------------------------------------------------------
    # Guard: skip if account.account model is not available (e.g. when
    # the module is loaded in a plain Python / test environment without a
    # live Odoo instance).
    if 'account.account' not in env:
        return

    ResCompany = env['res.company']
    ca_companies = ResCompany.search([('country_id.code', '=', 'CA')])
    if not ca_companies:
        # Fallback: process the current company even if country is not set
        ca_companies = ResCompany.search([('id', '=', env.company.id)])

    for company in ca_companies:
        ensure_payroll_accounts(env, company)
        journal = ensure_sal_journal(env, company)
        assign_journal_to_structures(env, journal)
