# Part of MHC. See LICENSE file for full copyright and licensing details.

import json
import logging
from datetime import datetime

from odoo import _, api, fields, models
from odoo.exceptions import UserError

from .cra_tax_update_line import _FEED_TO_RULE_PARAM, _SUPPORTED_PROVINCES

_logger = logging.getLogger(__name__)


class CraTaxUpdate(models.Model):
    _name = "cra.tax.update"
    _description = "CRA Tax Update"
    _inherit = ["mail.thread", "mail.activity.mixin"]
    _order = "effective_date desc, id desc"

    # ------------------------------------------------------------------
    # Fields
    # ------------------------------------------------------------------

    name = fields.Char(
        string="Name",
        compute="_compute_name",
        store=True,
    )
    effective_date = fields.Date(
        string="Effective Date",
        required=True,
        index=True,
        tracking=True,
    )
    published_at = fields.Datetime(
        string="Published At",
        help="UTC datetime when the feed was generated by the scraper.",
    )
    schema_version = fields.Char(string="Schema Version")
    jurisdiction = fields.Char(string="Jurisdiction", default="CA")
    source_urls = fields.Text(
        string="Source URLs",
        help="Newline-separated list of CRA source URLs used by the scraper.",
    )
    checksum_sha256 = fields.Char(string="Checksum (SHA-256)")
    signature_verified = fields.Boolean(
        string="Signature Verified",
        default=False,
        help="True if the GPG signature on the feed was successfully verified.",
    )
    state = fields.Selection(
        [
            ("draft", "Draft"),
            ("reviewed", "Reviewed"),
            ("applied", "Applied"),
            ("rejected", "Rejected"),
            ("superseded", "Superseded"),
        ],
        string="Status",
        default="draft",
        required=True,
        tracking=True,
        index=True,
    )
    payload_json = fields.Text(
        string="Payload JSON",
        help="Full JSON snapshot stored for audit purposes.",
    )
    line_ids = fields.One2many(
        "cra.tax.update.line",
        "update_id",
        string="Update Lines",
    )
    applied_by_id = fields.Many2one(
        "res.users",
        string="Applied By",
        readonly=True,
    )
    applied_at = fields.Datetime(
        string="Applied At",
        readonly=True,
    )
    notes = fields.Html(string="Notes")

    # ------------------------------------------------------------------
    # SQL constraints
    # ------------------------------------------------------------------

    _sql_constraints = [
        (
            "unique_effective_date_checksum",
            "UNIQUE(effective_date, checksum_sha256)",
            "A CRA Tax Update with this effective date and checksum already exists.",
        )
    ]

    # ------------------------------------------------------------------
    # Computed fields
    # ------------------------------------------------------------------

    @api.depends("effective_date")
    def _compute_name(self):
        for rec in self:
            if rec.effective_date:
                rec.name = _("CRA Update — effective %(date)s") % {
                    "date": rec.effective_date
                }
            else:
                rec.name = _("CRA Update (no date)")

    # ------------------------------------------------------------------
    # Cron entry point
    # ------------------------------------------------------------------

    @api.model
    def fetch_from_feed(self):
        """Fetch the CRA feed, verify checksum, and create a draft update.

        Called by the daily cron job.  Also honours the ``auto_apply``
        config parameter (off by default).
        """
        _logger.info("CRA Tax Update: starting feed fetch.")
        client = self.env["cra.feed.client"]
        try:
            payload = client.fetch()
            client.verify_checksum(payload)
        except UserError as exc:
            _logger.error("CRA Tax Update: feed fetch/verify failed: %s", exc)
            return

        effective_date_str = payload.get("effective_date")
        checksum = payload.get("checksum_sha256", "")

        existing = self.search(
            [
                ("effective_date", "=", effective_date_str),
                ("checksum_sha256", "=", checksum),
            ],
            limit=1,
        )
        if existing:
            _logger.info(
                "CRA Tax Update: feed unchanged (effective_date=%s checksum=%s…). "
                "No new record created.",
                effective_date_str,
                checksum[:16],
            )
            return

        _logger.info(
            "CRA Tax Update: new feed detected (effective_date=%s). Creating draft record.",
            effective_date_str,
        )
        update = self._create_from_payload(payload)

        # Notify HR payroll managers via mail activity
        self._notify_managers(update)

        # Auto-apply if configured (off by default)
        auto_apply = (
            self.env["ir.config_parameter"]
            .sudo()
            .get_param("l10n_ca_hr_payroll_cra_connector.auto_apply", default="False")
        )
        if auto_apply in ("True", "1", "true") and update.signature_verified:
            unmapped = update.line_ids.filtered(
                lambda l: l.selected and not l.rule_parameter_xml_id
            )
            if not unmapped:
                _logger.info(
                    "CRA Tax Update: auto-apply enabled and all lines mapped — applying."
                )
                update._do_apply(auto=True)
            else:
                _logger.warning(
                    "CRA Tax Update: auto-apply skipped — %d line(s) have no mapping.",
                    len(unmapped),
                )

        return update

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _create_from_payload(self, payload: dict):
        """Create a draft ``cra.tax.update`` record from a feed payload dict."""
        effective_date_str = payload.get("effective_date")
        published_at_str = payload.get("published_at", "")

        published_at = None
        if published_at_str:
            try:
                # Feed uses ISO 8601 with trailing Z; Odoo stores datetimes
                # as naive UTC so do NOT attach tzinfo.
                published_at = datetime.strptime(
                    published_at_str, "%Y-%m-%dT%H:%M:%SZ"
                )
            except ValueError:
                _logger.warning(
                    "CRA Tax Update: could not parse published_at=%s", published_at_str
                )

        source_urls = "\n".join(payload.get("source_urls", []))

        vals = {
            "effective_date": effective_date_str,
            "published_at": published_at,
            "schema_version": payload.get("schema_version", ""),
            "jurisdiction": payload.get("jurisdiction", "CA"),
            "source_urls": source_urls,
            "checksum_sha256": payload.get("checksum_sha256", ""),
            "signature_verified": False,
            "state": "draft",
            "payload_json": json.dumps(payload, indent=2, ensure_ascii=False),
        }
        update = self.create(vals)
        lines = update._build_lines_from_payload(payload)
        if lines:
            self.env["cra.tax.update.line"].create(lines)
        update.message_post(
            body=_(
                "Draft CRA Tax Update created automatically by the daily cron job. "
                "Effective date: %(date)s. %(count)d line(s) detected."
            )
            % {"date": effective_date_str, "count": len(lines)},
        )
        return update

    def _notify_managers(self, update):
        """Send an email + Odoo activity to HR payroll managers."""
        template = self.env.ref(
            "l10n_ca_hr_payroll_cra_connector.mail_template_cra_tax_update_new",
            raise_if_not_found=False,
        )
        if template:
            try:
                template.send_mail(update.id, force_send=False)
            except Exception as exc:  # noqa: BLE001
                _logger.warning(
                    "CRA Tax Update: could not send notification email: %s", exc
                )

        # Create a "To Do" activity for the HR payroll manager group
        activity_type = self.env.ref(
            "mail.mail_activity_data_todo", raise_if_not_found=False
        )
        if activity_type:
            update.activity_schedule(
                activity_type_id=activity_type.id,
                summary=_(
                    "Review CRA Tax Update — effective %(date)s"
                )
                % {"date": update.effective_date},
                note=_(
                    "A new CRA payroll tax update is available and awaits review. "
                    "Please open the record and verify each parameter change "
                    "with a qualified payroll professional before applying."
                ),
            )

    def _build_lines_from_payload(self, payload: dict) -> list[dict]:
        """Flatten feed payload into one line dict per scalar value.

        Returns a list of value dicts suitable for ``cra.tax.update.line.create``.
        """
        lines = []

        def _current_param_value(xml_id):
            """Return the current (latest) parameter value as a string, or ''."""
            if not xml_id:
                return ""
            try:
                param = self.env.ref(xml_id, raise_if_not_found=False)
                if not param:
                    return ""
                # hr.rule.parameter.value ordered by date_from desc
                latest_val = (
                    self.env["hr.rule.parameter.value"]
                    .search(
                        [("rule_parameter_id", "=", param.id)],
                        order="date_from desc",
                        limit=1,
                    )
                )
                if latest_val:
                    return str(latest_val.parameter_value)
            except Exception as exc:  # noqa: BLE001
                _logger.warning(
                    "CRA Tax Update: could not read current value for %s: %s",
                    xml_id,
                    exc,
                )
            return ""

        def _add(path, value, vtype="float"):
            xml_id = _FEED_TO_RULE_PARAM.get(path)
            old_val = _current_param_value(xml_id) if xml_id else ""
            lines.append(
                {
                    "update_id": self.id,
                    "path": path,
                    "rule_parameter_xml_id": xml_id or "",
                    "old_value": old_val,
                    "new_value": str(value) if value is not None else "",
                    "value_type": vtype,
                    "selected": True,
                }
            )

        # CPP
        cpp = payload.get("cpp", {})
        _add("cpp.rate", cpp.get("rate"))
        _add("cpp.ympe", cpp.get("ympe"))
        _add("cpp.basic_exemption", cpp.get("basic_exemption"))

        # CPP2
        cpp2 = payload.get("cpp2", {})
        _add("cpp2.rate", cpp2.get("rate"))
        _add("cpp2.yampe", cpp2.get("yampe"))

        # EI
        ei = payload.get("ei", {})
        _add("ei.rate", ei.get("rate"))
        _add("ei.max_insurable_earnings", ei.get("max_insurable_earnings"))

        # Federal
        federal = payload.get("federal", {})
        bpaf = federal.get("bpaf", {})
        _add("federal.bpaf.max", bpaf.get("max"))
        _add("federal.bpaf.min", bpaf.get("min"))
        _add("federal.k1_rate", federal.get("k1_rate"))
        for idx, bracket in enumerate(federal.get("tax_brackets", [])):
            if bracket.get("up_to") is not None:
                _add(f"federal.tax_brackets[{idx}].up_to", bracket["up_to"])
            _add(f"federal.tax_brackets[{idx}].rate", bracket.get("rate"))

        # Provinces (BPA scalars; bracket data noted as JSON type)
        for prov_code, prov_data in payload.get("provinces", {}).items():
            if prov_code not in _SUPPORTED_PROVINCES:
                continue
            bpa = prov_data.get("bpa")
            if bpa is not None:
                _add(f"provinces.{prov_code}.bpa", bpa)
            for idx, bracket in enumerate(prov_data.get("tax_brackets", [])):
                path_up = f"provinces.{prov_code}.tax_brackets[{idx}].up_to"
                path_rate = f"provinces.{prov_code}.tax_brackets[{idx}].rate"
                if bracket.get("up_to") is not None:
                    _add(path_up, bracket["up_to"])
                _add(path_rate, bracket.get("rate"))

        return lines

    # ------------------------------------------------------------------
    # State transitions
    # ------------------------------------------------------------------

    def action_review(self):
        self.ensure_one()
        if self.state != "draft":
            raise UserError(_("Only draft updates can be marked as reviewed."))
        self.state = "reviewed"
        self.message_post(body=_("Update marked as reviewed."))

    def action_reject(self):
        self.ensure_one()
        if self.state in ("applied", "superseded"):
            raise UserError(_("Cannot reject an already applied or superseded update."))
        self.state = "rejected"
        self.message_post(body=_("Update rejected."))

    def action_open_apply_wizard(self):
        self.ensure_one()
        if self.state not in ("draft", "reviewed"):
            raise UserError(
                _("Only draft or reviewed updates can be applied.")
            )
        return {
            "type": "ir.actions.act_window",
            "name": _("Apply CRA Tax Update"),
            "res_model": "cra.tax.update.apply.wizard",
            "view_mode": "form",
            "target": "new",
            "context": {
                "default_update_id": self.id,
            },
        }

    def action_refetch(self):
        """Trigger a manual feed fetch from the form view."""
        self.env["cra.tax.update"].fetch_from_feed()
        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": _("Feed Refetch"),
                "message": _("Feed refetch triggered. Check the list for new updates."),
                "type": "info",
                "sticky": False,
            },
        }

    def _do_apply(self, auto=False):
        """Internal: write parameter values and mark this update as applied.

        Used both by the wizard and by auto-apply.
        """
        self.ensure_one()
        effective_date = self.effective_date
        for line in self.line_ids.filtered(
            lambda l: l.selected and l.rule_parameter_xml_id
        ):
            try:
                param = self.env.ref(
                    line.rule_parameter_xml_id, raise_if_not_found=True
                )
            except ValueError:
                _logger.warning(
                    "CRA Tax Update: xml id %s not found — skipping line %s.",
                    line.rule_parameter_xml_id,
                    line.path,
                )
                continue
            existing_val = self.env["hr.rule.parameter.value"].search(
                [
                    ("rule_parameter_id", "=", param.id),
                    ("date_from", "=", effective_date),
                ],
                limit=1,
            )
            if existing_val:
                existing_val.parameter_value = line.new_value
            else:
                self.env["hr.rule.parameter.value"].create(
                    {
                        "rule_parameter_id": param.id,
                        "date_from": effective_date,
                        "parameter_value": line.new_value,
                    }
                )

        self.write(
            {
                "state": "applied",
                "applied_by_id": self.env.user.id,
                "applied_at": fields.Datetime.now(),
            }
        )

        # Mark earlier applied updates as superseded
        earlier = self.search(
            [
                ("state", "=", "applied"),
                ("effective_date", "<", effective_date),
                ("id", "!=", self.id),
            ]
        )
        if earlier:
            earlier.write({"state": "superseded"})

        prefix = _("Auto-applied") if auto else _("Applied")
        self.message_post(
            body=_(
                "%s by %s. "
                "%d line(s) written to hr.rule.parameter."
            )
            % {
                "prefix": prefix,
                "user": self.env.user.name,
                "applied": len(
                    self.line_ids.filtered(
                        lambda l: l.selected and l.rule_parameter_xml_id
                    )
                ),
            }
        )
